name = "vhlink"
type = "javascript"
account_id = "566ccbfc5b9008e65ab6490435cda9a3"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "77612e844ef647009a28a1153fcd0a96", preview_id = "77612e844ef647009a28a1153fcd0a96" }
]
